version: '3.1'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'postgres'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: